image: gitpod/workspace-full

tasks:
  - init: |
      pip install -r requirements.txt || pip install pandas jupyter matplotlib seaborn scipy
  - name: Start Jupyter Notebook
    command: |
      echo "📚 Starting Jupyter Notebook..."
      nohup jupyter notebook \
        --NotebookApp.token='' \
        --NotebookApp.password='' \
        --NotebookApp.allow_origin='*' \
        --NotebookApp.allow_remote_access=True \
        --NotebookApp.ip=0.0.0.0 \
        --NotebookApp.port=8888 \
        > jupyter.log 2>&1 &

      echo "✅ Jupyter is launching in the background..."
      echo ""
      echo "🌐 Open this in your browser:"
      echo "👉 https://8888-$(gp url 8888 | sed 's|^https://||')/tree"

ports:
  - port: 8888
    onOpen: open-preview
    visibility: public
