image: gitpod/workspace-full

tasks:
  - init: |
      pip install -r requirements.txt || pip install pandas jupyter matplotlib seaborn scipy
  - name: Start Jupyter Notebook
    command: |
      nohup jupyter notebook \
        --NotebookApp.token='' \
        --NotebookApp.password='' \
        --NotebookApp.allow_origin='*' \
        --NotebookApp.allow_remote_access=True \
        --NotebookApp.ip=0.0.0.0 \
        --NotebookApp.port=8888 \
        > jupyter.log 2>&1 &

      echo "✅ Jupyter is launching in the background..."
      echo "🌐 Open this in your browser:"
      echo "👉 $(gp url 8888)/tree"

ports:
  - port: 8888
    onOpen: open-preview
    visibility: public
