image: gitpod/workspace-full

tasks:
  - name: Start Jupyter Notebook
    command: |
      pip install -r requirements.txt || pip install pandas jupyter matplotlib seaborn scipy
      jupyter notebook --NotebookApp.token='' --NotebookApp.password='' \
                       --NotebookApp.allow_origin='*' \
                       --NotebookApp.allow_remote_access=True \
                       --NotebookApp.ip=0.0.0.0 \
                       --NotebookApp.port=8888

ports:
  - port: 8888
    onOpen: open-preview
    visibility: public
