image: gitpod/workspace-full

tasks:
  - name: Start Jupyter Notebook
    command: |
      pip install -r requirements.txt || pip install pandas jupyter matplotlib seaborn scipy
      nohup jupyter notebook \
        --NotebookApp.token='' \
        --NotebookApp.password='' \
        --NotebookApp.allow_origin='*' \
        --NotebookApp.allow_remote_access=True \
        --NotebookApp.ip=0.0.0.0 \
        --NotebookApp.port=8888 \
        2>&1 | grep -v "file://" > /dev/null &

      echo "✅ Jupyter is launching in the background..."
      echo "🌐 Open this in your browser:"
      echo "$(gp url 8888)/tree"

